---
- name: Install LLNG Repository KEY
  copy: src=rpm-gpg-key-ow2 dest=/tmp/gpg-key-ow2 owner=root group=root mode=0644
- name: Check for Missing Trusted Key
  changed_when: "has_apt_key.rc != 0"
  failed_when: false
  register: has_apt_key
  shell: apt-key list | sed 's| ||g' | grep -i {{ lemonldap_gpg_pubkey_id }}
- name: Import LLNG GPG KEY
  shell: apt-key add gpg-key-ow2 chdir=/tmp
  when: has_apt_key is defined and has_apt_key.rc is defined and has_apt_key.rc != 0
- name: Install LLNG Debian Repository
  copy: src=debian_lemonldap-ng.list dest=/etc/apt/sources.list.d/lemonldap-ng.list owner=root group=root mode=0644
  register: llng_repo
- name: Refresh Packages Cache
  apt: update_cache=yes
  when: llng_repo is defined and llng_repo.changed is defined and llng_repo.changed == True
- name: Install Webserver Dependencies (1/2)
  apt: name={{ item }} state=present
  when: lemonldap_webserver | default('apache') in [ 'apache', 'httpd' ]
  with_items: [ "apache2", "libapache2-mod-perl2", "libapache2-mod-fcgid", "apt-transport-https", "liblasso-perl" ]
- name: Install Webserver Dependencies (2/2)
  apt: name={{ item }} state=present
  when: lemonldap_webserver | default('apache') == 'nginx'
  with_items: [ "nginx", "nginx-extras", "lemonldap-ng-fastcgi-server", "apt-transport-https", "liblasso-perl" ]
- name: Install LLNG
  apt: name={{ item }} state=present
  with_items: [ "lemonldap-ng", "lemonldap-ng-fr-doc" ]
