---
- name: Install LLNG Repository KEY
  copy:
    src: rpm-gpg-key-ow2
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-OW2
    owner: root
    group: root
    mode: 0644

- name: Import LLNG GPG KEY
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-OW2
    state: present

- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Install LLNG Enterprise Linux Repository
  copy:
    src: redhat_lemonldap-ng.repo
    dest: /etc/yum.repos.d/lemonldap-ng.repo
    owner: root
    group: root
    mode: 0644
  register: llng_repo

- name: Install Webserver Dependencies (1/2)
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  when: lemonldap_webserver | default('apache') in [ 'apache', 'httpd' ]
  with_items:
    - httpd
    - mod_perl
    - mod_fcgid
    - perl-LWP-Protocol-https

- name: Install Webserver Dependencies (2/2)
  yum:
    name: "{{ item }}"
    state: present
  when: lemonldap_webserver | default('apache') == 'nginx'
  with_items:
    - nginx
    - lemonldap-ng-fastcgi-server
    - perl-LWP-Protocol-https

- name: Enable Apache
  service:
    name: httpd
    state: started
    enabled: yes
  when: lemonldap_webserver | default('apache') in [ 'apache', 'httpd' ]

- name: Enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes
  when: lemonldap_webserver | default('apache') == 'nginx'

- name: Install LLNG
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - lemonldap-ng
    - lemonldap-ng-fr-doc
