---
- name: Find conf file to edit
  find:
    paths: /etc/lemonldap-ng/
    patterns: "^.*?{{ lemonldap_webserver }}.*?\\.conf$"
    use_regex: yes
  register: lemonldap_webserver_conf_search_res

- name: Find apache conf file to edit
  find:
    paths: /etc/httpd/conf.d/
    patterns: "^z-lemonldap-ng.*?\\.conf$"
    use_regex: yes
  register: lemonldap_apache_conf_search_res

- name: Find ini file to edit
  find:
    paths: /etc/lemonldap-ng/
    patterns: "^.*?\\.ini$"
    use_regex: yes
  register: lemonldap_ini_search_rest

- name: Check LLNG Current Domain
  replace:
    path: "{{ item.path }}"
    regexp: '^(.*)example\.com(.*)$'
    replace: '\1{{ lemonldap_domain }}\2'
  when: lemonldap_domain | default('example.com') != 'example.com'
  with_items:
    - "{{ lemonldap_webserver_conf_search_res.files }}"
    - "{{ lemonldap_apache_conf_search_res.files }}"
    - "{{ lemonldap_ini_search_rest.files }}"
    - { 'path': '/var/lib/lemonldap-ng/conf/lmConf-1.json' }
  notify:
    - Reload Webserver
    - Enable and reload lemonldap

- name: symlink webserver config file
  file:
    src: "{{ item.path }}"
    dest: "/etc/nginx/sites-enabled/{{ item.path | basename }}"
    state: link
  with_items: "{{ lemonldap_webserver_conf_search_res.files }}"
  when: lemonldap_webserver == 'nginx'
  notify: Reload Webserver

- name: Enable apache lemonldap config
  command: "a2ensite {{ item }}"
  with_items:
    - portal-apache2
    - manager-apache2
    - handler-apache2
  when:
    - lemonldap_webserver == 'apache'
    - ansible_os_family == "Debian"
  notify: Reload Webserver

- name: Enable apache module required by lemonldap config
  command: "a2enmod {{ item }}"
  with_items:
    - headers
    - rewrite
  when:
    - lemonldap_webserver == 'apache'
    - ansible_os_family == "Debian"
  notify: Reload Webserver
