
---
- name: Needs Fixing Apache pre-2.3 SOAP Configuration
  changed_when: "need_pre23_change is defined and need_pre23_change.rc is defined and need_pre23_change.rc == 0"
  failed_when: false
  shell: grep "{{ 'Deny' if (lemonldap_do_soap | default(False) == True) else 'Allow' }} from all" portal-apache*conf chdir=/etc/lemonldap-ng
  register: need_pre23_change
  when: lemonldap_webserver | default('apache') in [ 'apache', 'httpd' ]
- name: Needs Fixing Apache post-2.3 SOAP Configuration
  changed_when: "need_post23_change is defined and need_post23_change.rc is defined and need_post23_change.rc == 0"
  failed_when: false
  shell: grep "Require all {{ 'denied' if (lemonldap_do_soap | default(False) == True) else 'granted' }}" portal-apache*conf chdir=/etc/lemonldap-ng
  register: need_post23_change
  when: lemonldap_webserver | default('apache') in [ 'apache', 'httpd' ]
- name: Needs Fixing Nginx SOAP Configuration
  changed_when: "need_nginx_change is defined and need_nginx_change.rc is defined and need_nginx_change.rc == 0"
  failed_when: false
  shell: grep "{{ 'deny' if (lemonldap_do_soap | default(False) == True) else 'allow' }} all;" portal-nginx.conf chdir=/etc/lemonldap-ng
  register: need_nginx_change
  when: lemonldap_webserver | default('apache') == 'nginx'
- name: Fixes Apache pre-2.3 SOAP Configuration
  notify: Reload Webserver
  shell: sed -i "s/{{ 'Deny' if (lemonldap_do_soap | default(False) == True) else 'Allow' }} from all.*/{{ 'Allow' if (lemonldap_do_soap | default(False) == True) else 'Deny' }} from all/g" portal-apache*conf chdir=/etc/lemonldap-ng
  when: need_pre23_change is defined and need_pre23_change.rc is defined and need_pre23_change.rc == 0
- name: Fixes Apache post-2.3 SOAP Configuration
  notify: Reload Webserver
  shell: sed -i "s/Require all {{ 'denied' if (lemonldap_do_soap | default(False) == True) else 'granted' }}.*/Require all {{ 'granted' if (lemonldap_do_soap | default(False) == True) else 'denied' }}/g" portal-apache*conf chdir=/etc/lemonldap-ng
  when: need_post23_change is defined and need_post23_change.rc is defined and need_post23_change.rc == 0
- name: Fixes Nginx SOAP Configuration
  notify: Reload Webserver
  shell: sed -i "s/{{ 'deny' if (lemonldap_do_soap | default(False) == True) else 'allow' }} all.*/{{ 'allow' if (lemonldap_do_soap | default(False) == True) else 'deny' }} all;/g" portal-nginx.conf chdir=/etc/lemonldap-ng
  when: need_nginx_change is defined and need_nginx_change.rc is defined and need_nginx_change.rc == 0
